alias dcapi='docker compose run --rm backend bash'
alias dcm='docker compose run --rm backend npm run migration'
alias dcu='docker compose up'
alias dcb='docker compose build'
alias dcd='docker compose down'
alias ..='cd ..'
git config --global alias.shove 'push -u origin HEAD'