
version: '3.8'

services:
  frontend:
   
    image: frontend

    build: ./frontend
      
    environment:
      
      NODE_ENV: production
    
    ports:
    
      - 3000:3000
      - 3001:3001

    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm run dev -- --host 0.0.0.0

  backend:

    build: ./backend

    ports:

      - 8080:8080

    volumes:

      - .:/usr/src/app

    depends_on:

      - postgres_db

  postgres_db:

    image: postgres

    environment:

      POSTGRES_DB: mydatabase

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: password


    ports:

      - "5432:5432"