
version: '3.8'

services:

  backend:

    build: ./backend

    ports:

      - "3000:3000"

    volumes:

      - .:/usr/src/app

    depends_on:

      - postgres_db

  postgres_db:

    image: postgres

    environment:

      POSTGRES_DB: mydatabase

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: password


    ports:

      - "5432:5432"